Домашняя работа №1
Orianka13/FocusStartHomeworks pull request #1
Opened 2021-10-29 16:02 UTC by Orianka13

Консольное приложение с интерфейсом взаимодействия с пользователем.
Реализован следующий функционал:
1. Добавление нового автомобиля
2. Вывод списка добавленных автомобилей
3. Вывод списка автомобилей с использованием фильтра по типу кузова автомобиля

2021-10-30 04:20 UTC, AlexRaptor reviewed
Для первого ДЗ - работа хорошая.
С рекурсией нужно быть поосторожнее - её глубина ограничена размером стэка и приложение может закрашиться. 
ИМХО: лучше было бы сделать через while, а не рекурсию

2021-10-30 04:20 UTC, AlexRaptor commented on FocusStartHomeworks/FocusStartHomeworks/main.swift
> +private func bodyType(numberOfType: Int) -> Body {
Место этого метода внутри enum-а Body

2021-10-30 04:20 UTC, AlexRaptor commented on FocusStartHomeworks/FocusStartHomeworks/main.swift
> +    case 6:
6-ку можно не обрабатывать, она попадает под default

2021-10-30 04:20 UTC, AlexRaptor commented on FocusStartHomeworks/FocusStartHomeworks/main.swift
> +        menu()
В настоящий момент из menu() выхода нет - оно постоянно будет погружаться всё глубже и глубже в рекурсию. Но если вдруг что-то поправится и из menu() произойдёт выход, то мы перейдём далее по методу в цикл for. Нужно минимум его поместить в else { for ... }

2021-10-31 08:26 UTC, AlexRaptor requested changes
Поправь, плиз, замечания.
И ещё - домашка называется как весь git-проект. Когда смежится, будет не удобно. Может переименовать? Но это так, не критикл

2021-10-31 08:26 UTC, AlexRaptor commented on FocusStartHomeworks/FocusStartHomeworks/main.swift
> +    print("Укажите тип кузова:\n1 - Седан \n2 - Универсальный\n3 - Кабриолет\n4 - Пикап\n5 - Кроссовер\n6 - Другой")
При каждом добавлении нового типа кузова нужно будет править этот метод.

- [ ] поддержи в `enum Body` `CaseIterable` и распечатай эту подсказку через `for enumarated`
- [ ] значение 6 как "исключительное" - не хороший выбор, при каждом добавлении нового типа нужно будет сдвигать цифру. Если уж на то пошло, то может "-1" ?

2021-10-31 11:10 UTC, Orianka13 commented on FocusStartHomeworks/FocusStartHomeworks/main.swift
> +private func bodyType(numberOfType: Int) -> Body {
Метод заменила на цикл (проще переиспользовать), убрала в enum

2021-10-31 11:11 UTC, Orianka13 commented on FocusStartHomeworks/FocusStartHomeworks/main.swift
> +        menu()
Рекурсию убрала (использовала цикл while), метод вызывается только 1 раз

2021-10-31 11:12 UTC, Orianka13 commented on FocusStartHomeworks/FocusStartHomeworks/main.swift
> +    print("Укажите тип кузова:\n1 - Седан \n2 - Универсальный\n3 - Кабриолет\n4 - Пикап\n5 - Кроссовер\n6 - Другой")
Вывод переделала, значение "Другой" поставила на индекс 0

2021-10-31 12:39 UTC, AlexRaptor approved these changes

2021-10-31 12:45 UTC, merged